.TH "GNOME-PHONE-MANAGER" "1" "January 2011" "Francesco Namuri" "User Commands"
.SH "NAME"
gnome\-phone\-manager \- Manage your mobile phone
.SH "USAGE"
.B gnome-phone-manager
[\-\-identify\ <baddr>] [\-\-config] [\-d|\-\-debug]] [\-\-display=DISPLAY]
.SH "DESCRIPTION"
This manual page documents briefly the \fBgnome\-phone\-manager\fR command.

\fBgnome\-phone\-manager\fR is a program created to allow you to control aspects of your mobile phone from your GNOME 2 desktop.
.TP
Current features include:
.BR \-
Runs in the background; indicates status on the panel notification area,
.br
.BR \- 
Display on\-screen alert when text message (SMS) arrives,
.br
.BR \- 
Text message (SMS) sending facility,
.br
.BR \- 
Evolution Addressbook integration.
.SH "OPTIONS"
.SS "Help Options:"
.TP 
.BI \-?,\ \fB\-\-help\fR
Show help options
.TP 
\fB\-\-help\-all\fR
Show all help options
.TP 
\fB\-\-help\-gtk\fR
Show GTK+ Options
.TP 
\fB\-\-help\-gst\fR
Show GStreamer Options
.SS "Application Options:"
.TP
.BI \-\-identify\fR=\fIPORT\fR
Show model name of the phone connected to the given
.IR PORT
which can be a Bluetooth address or a device file
.TP
.BI \-\-config\fR=\fIPORT\fR
Write the configuration file for gnokii debugging of the phone connected to the given
.IR PORT
which can be a Bluetooth address or a device file
.TP
.BI \-d,\ \fB\-\-debug\fR
Enable debug
.TP 
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.SH "SEE ALSO"
Homepage: http://live.gnome.org/PhoneManager
.SH "AUTHOR"
\fBgnome\-phone\-manager\fR was written by Bastien Nocera <<hadess@hadess.net>> and Edd Dumbill <edd@usefullinc.com>

This manual page was written by Francesco Namuri <francesco@namuri.it> for the Debian project (but may be used by others).
