/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Message received");
gchar *s = N_("_Reply");
gchar *s = N_("<span weight=\"bold\" size=\"larger\">Your mobile phone has received a message.</span>");
gchar *s = N_("date and time of message");
gchar *s = N_("sender name and number");
gchar *s = N_("<span weight=\"bold\">Date</span>");
gchar *s = N_("<span weight=\"bold\">Sender</span>");
gchar *s = N_("message contents");
gchar *s = N_("Phone Manager Preferences");
gchar *s = N_("Use Bluetooth wireless networking to connect to your phone");
gchar *s = N_("Bluetooth");
gchar *s = N_("Update the list of Bluetooth-enabled mobile phones");
gchar *s = N_("Update");
gchar *s = N_("Connect using serial port 1, also known as COM1 or /dev/ttyS0");
gchar *s = N_("Serial port 1 (/dev/ttyS0)");
gchar *s = N_("Connect using serial port 2, also known as COM2 or /dev/ttyS1");
gchar *s = N_("Serial port 2 (/dev/ttyS1)");
gchar *s = N_("Connect using infrared communication");
gchar *s = N_("Infra red (/dev/ircomm)");
gchar *s = N_("Connect using an alternative serial device");
gchar *s = N_("Other port");
gchar *s = N_("Alternative device filename, e.g. /dev/ttyS3");
gchar *s = N_("/dev/ttyS2");
gchar *s = N_("*");
gchar *s = N_("Phone connection");
gchar *s = N_("Always try and reconnect whenever a connection is not immediately available. Use this with Bluetooth to ensure your phone connects whenever it comes in range.");
gchar *s = N_("Automatically retry connections");
gchar *s = N_("Connection");
gchar *s = N_("Bluetooth operation in progress");
gchar *s = N_("<span weight=\"bold\" size=\"larger\">Bluetooth device discovery in progress</span>");
gchar *s = N_("Current status.");
gchar *s = N_("Send message");
gchar *s = N_("_Send");
gchar *s = N_("<span weight=\"bold\" size=\"larger\">Send a text message.</span>");
gchar *s = N_("160");
gchar *s = N_("<span weight=\"bold\">Characters left</span>");
gchar *s = N_("<span weight=\"bold\">Recipient</span>");
gchar *s = N_("message content");
gchar *s = N_("*");
