/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Message Received");
gchar *s = N_("_Reply");
gchar *s = N_("<span weight=\"bold\" size=\"larger\">You have received a message</span>");
gchar *s = N_("date and time of message");
gchar *s = N_("sender name and number");
gchar *s = N_("<span weight=\"bold\">Sender</span>");
gchar *s = N_("<span weight=\"bold\">Date</span>");
gchar *s = N_("message contents");
gchar *s = N_("Phone Manager Preferences");
gchar *s = N_("_Pop-up window for new messages");
gchar *s = N_("Play _sound when messages arrive");
gchar *s = N_("<b>Alerting</b>");
gchar *s = N_("Interface");
gchar *s = N_("Use Bluetooth wireless networking to connect to your phone");
gchar *s = N_("_Bluetooth");
gchar *s = N_("Choose a Bluetooth-enabled mobile phone to connect to.");
gchar *s = N_("Choo_se");
gchar *s = N_("Connect using serial port 1, also known as COM1 or /dev/ttyS0");
gchar *s = N_("Serial port _1 (/dev/ttyS0)");
gchar *s = N_("Connect using serial port 2, also known as COM2 or /dev/ttyS1");
gchar *s = N_("Serial port _2 (/dev/ttyS1)");
gchar *s = N_("Connect using infrared communication");
gchar *s = N_("_Infra red (/dev/ircomm)");
gchar *s = N_("Connect using an alternative serial device");
gchar *s = N_("Other _port");
gchar *s = N_("Alternative device filename, e.g. /dev/ttyS3");
gchar *s = N_("/dev/ttyS2");
gchar *s = N_("*");
gchar *s = N_("<b>Phone Connection</b>");
gchar *s = N_("Always try and reconnect whenever a connection is not immediately available. Use this with Bluetooth to ensure your phone connects whenever it comes in range.");
gchar *s = N_("Automatically _retry connections");
gchar *s = N_("<b>Error Handling</b>");
gchar *s = N_("Connection");
gchar *s = N_("Send Message");
gchar *s = N_("_Send");
gchar *s = N_("<span weight=\"bold\" size=\"larger\">Enter your text message</span>");
gchar *s = N_("160");
gchar *s = N_("Characters left:");
gchar *s = N_("Number of characters left in the message");
gchar *s = N_("_Recipient:");
gchar *s = N_("Enter the number you wish to send a message to.");
gchar *s = N_("*");
gchar *s = N_("_Message:");
gchar *s = N_("Enter the text message you want to send.");
gchar *s = N_("message content");
gchar *s = N_("message body");
